"""Rendering, CModel, and entity display configuration constants."""

ENABLE_PFF_CMODEL = True
CMODEL_DEDUP_EDGES = True

MAX_SEGMENT_LOD_CACHE = 64
MAX_ROTATED_SEGMENT_CACHE = 96
MAX_ROTATED_BOUNDS_CACHE = 96
ZOOM_SETTLE_DELAY_MS = 140
ZOOM_FAST_RENDER_DELAY_MS = 16
LOD_NODE_HEAVY_COUNT = 5000
LOD_HIDE_RADIUS_ZOOM = 0.75
LOD_HIDE_EDGES_ZOOM = 0.45
LOD_HIDE_ENTITIES_ZOOM = 0.22
LOD_SIMPLE_NODES_ZOOM = 0.65

CMODEL_PRELOAD_ON_BMS_LOAD = True
CMODEL_REQUEST_ON_DRAW = True
CMODEL_PRELOAD_CATEGORIES = {'building', 'decoration', 'object', 'vehicle'}
CMODEL_PRELOAD_MAX_TYPES = 0
CMODEL_LAZY_DECORATION_MIN_ZOOM = 0.0
CMODEL_LAZY_DECORATION_MIN_RPX = 0.0
CMODEL_LAZY_FOLIAGE_MIN_ZOOM = 6.0
CMODEL_LAZY_FOLIAGE_MIN_RPX = 48.0

AUTO_TRIM_DERIVED_CACHES = True
AUTO_TRIM_AFTER_SETTLE_MS = 1600
AUTO_TRIM_ROTATED_TOTAL = 120
AUTO_TRIM_COOLDOWN_MS = 2500

STATIC_ENTITY_LAYER_CACHE = True
STATIC_ENTITY_LAYER_PAD_PX = 320
STATIC_ENTITY_LAYER_ZOOM_EPS = 0.001
STATIC_ENTITY_LAYER_MIN_ENTITIES = 1
STATIC_ENTITY_LAYER_CLEAR_DERIVED_AFTER_REBUILD = True

ZOOM_BITMAP_PREVIEW = True
ZOOM_PREVIEW_RESAMPLE = 'bilinear'
ZOOM_PREVIEW_THROTTLE_MS = 33
ZOOM_EXACT_REDRAW_AFTER_SETTLE_MS = 260

ZOOM_STATIC_LAYER_PREVIEW = True
ZOOM_STATIC_LAYER_PREVIEW_FALLBACK_BITMAP = True

CMODEL_DETAIL_MIN_ZOOM = 0.0
CMODEL_BOX_ZOOM = 0.0
CMODEL_MAX_DRAW_SEGS = 1000000
CMODEL_WORKER_SLEEP = 0.025
CMODEL_FULL_DETAIL_ZOOM = 2.0
CMODEL_FULL_DETAIL_BUILDING_ZOOM = 2.0
CMODEL_FULL_DETAIL_OBJECT_ZOOM = 2.0
CMODEL_FULL_DETAIL_DECORATION_ZOOM = 3.0
CMODEL_FULL_DETAIL_HEAVY_ZOOM = 3.5
CMODEL_HEAVY_SEG_THRESHOLD = 1600
CMODEL_HUSK_SMALL_SEG_LIMIT = 180
CMODEL_HUSK_MAX_BOUNDARY_SEGS = 350
CMODEL_HUSK_QUANT = 0.02
CMODEL_SKIP_CATEGORIES = {'person', 'marker', 'effect', 'powerup'}
CMODEL_STATIC_CATEGORIES = {'building', 'decoration', 'object', 'vehicle', 'foliage'}
CMODEL_DECORATION_REQUIRE_PHYSICAL = True
CMODEL_DECORATION_PHYSICAL_KEYS = {'hp', 'armor', 'husk', 'ai_function', 'move_function', 'kz'}
CMODEL_DECORATION_ALLOW_GRAPHIC_PREFIXES = ('baricd', 'mwal', 'bfence', 'fountn', 'ncar', 'nbus', 'ntrk', 'etek', 'wcrate', 'wpnct', 'vndcrt')
CMODEL_DECORATION_SKIP_ATTRS = {'notool', 'noctool'}
CMODEL_MAX_REQUESTS_PER_RENDER = 3
CMODEL_MAX_QUEUE_SIZE = 48
CMODEL_LOAD_IDLE_DELAY = 0.0
CMODEL_ENTITY_HIDE_ZOOM = 999.0
CMODEL_FIRST_PASS_MARGIN_PX = 420

ENTITY_RENDER_MODE = "stable_full"
STABLE_ENTITY_OUTLINES = True
FOLIAGE_HULL_ONLY = False

BUILDING_FULL_DETAIL_ZOOM = 2.0
OBJECT_FULL_DETAIL_ZOOM = 5.5
DECORATION_FULL_DETAIL_ZOOM = 9.0
VEHICLE_FULL_DETAIL_ZOOM = 5.5
HEAVY_FULL_DETAIL_ZOOM = 14.0
HEAVY_SEG_THRESHOLD = 2200

MAX_VISIBLE_LINES_PER_ENTITY = 6000
CMODEL_FAST_CULL_MARGIN_PX = 220
CMODEL_FAST_LINES_PER_ENTITY = 900
BUILDINGS_BYPASS_LINE_BUDGET_AT_FULL_ZOOM = True
RADIUS_FILL_MIN_ZOOM = 8.0

SHOW_CONTEXT_ENTITY_MARKERS = False
CONTEXT_MARKER_SIZE_PX = 3
CONTEXT_MARKER_MIN_ZOOM = 0.0
CONTEXT_MARKER_MAX_ZOOM = 999.0

CMODEL_EXCLUDE_GRAPHIC_PREFIXES = ("fx",)

CONTEXT_ONLY_GRAPHIC_PREFIXES = (
    "fx",
    "trash",
    "pos_",
)

CONTEXT_ONLY_GRAPHICS = {
    "fan01",
    "bed01", "bed02", "bed03",
    "wtrsh1", "wtrsh2", "wtrsh3", "wtrsh4",
}
